### ISSUE TITLE
Issue with python 3.8

### ISSUE THREAD

**Issue by GiulioRossetti** [fsssosei/shuffle_graph#1]
Hi,
I'm the maintainer of cdlib, a python package that relies on     shuffle-graph. Since the last update of your library on the 30th of October I'm experiencing issues during the installation on python 3.8 envs (everything works fine under python 3.6 and 3.7).

Here's the error I get:

`ERROR: No matching distribution found for completely-shuffle>=0.9.2 (from shuffle-graph>=1.1.2->ASLPAw->cdlib==0.1.9)`

Could you please look into it?
It seems something related to a pinned missing dependency.

Best,
Giulio

**Comment by fsssosei** [comment]
> 
> 
> 你好
> 我是cdlib的维护者，cdlib是一个依赖shuffle-graph的python软件包。自从10月30日对库进行最后一次更新以来，我在python3.8envs上安装期间遇到问题（在python3.6和3.7下一切正常。）
> 
> 这是我得到的错误：
> 
> `ERROR: No matching distribution found for completely-shuffle>=0.9.2 (from shuffle-graph>=1.1.2->ASLPAw->cdlib==0.1.9)`
> 
> 你能调查一下吗？
> 似乎与固定缺少的依赖关系有关。
> 
> 最好，
> 朱利奥

I am very sorry that it could not be maintained during this period.
Issue fixed.
