### ISSUE TITLE
With 2.0.2 : module 'shuffle_graph_package.shuffle_graph_module' has no attribute 'prng_algorithms_tuple'

### ISSUE THREAD

**Issue by glestel** [fsssosei/shuffle_graph#2]
Hi,

I was trying to install shuffle graph in a fresh python 3.8 environment and I can't import the statement : 
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shuffle_graph_package import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/glestel/test_shuffle/lib/python3.8/site-packages/shuffle_graph_package/__init__.py", line 19, in <module>
    from shuffle_graph_package.shuffle_graph_module import *
AttributeError: module 'shuffle_graph_package.shuffle_graph_module' has no attribute 'prng_algorithms_tuple'
```
Here is the content of my dependencies 
```
$ pip freeze
complete-shuffle==0.9.7
decorator==4.4.2
gmpy2==2.0.8
networkx==2.5
pure-nrng==0.8.3
pure-prng==0.9.4
shuffle-graph==2.0.2
```

It works correctly if I fix the version to `1.1.2` which was the previous main release.

Best regards.

**Comment by fsssosei** [comment]
I am very sorry that it could not be maintained during this period.
Issue fixed

> 
> 
> 你好
> 
> 我试图在全新的python3.8环境中安装随机播放图，但无法导入该语句：
> 
> ```
> Python 3.8.5 (default, Jul 28 2020, 12:59:40)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from shuffle_graph_package import *
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/glestel/test_shuffle/lib/python3.8/site-packages/shuffle_graph_package/__init__.py", line 19, in <module>
>     from shuffle_graph_package.shuffle_graph_module import *
> AttributeError: module 'shuffle_graph_package.shuffle_graph_module' has no attribute 'prng_algorithms_tuple'
> ```
> 
> 这是我依赖项的内容
> 
> ```
> $ pip freeze
> complete-shuffle==0.9.7
> decorator==4.4.2
> gmpy2==2.0.8
> networkx==2.5
> pure-nrng==0.8.3
> pure-prng==0.9.4
> shuffle-graph==2.0.2
> ```
> 
> 如果我将版本修复为`1.1.2`这是先前的主要版本。
> 
> 最好的祝福。

I am very sorry that it could not be maintained during this period.
Issue fixed.
